// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD71HIt8GCjVA48kWlVI5OJ_MD_ampyrUE',
    appId: '1:862048823819:web:a79e9584ced3551117f50e',
    messagingSenderId: '862048823819',
    projectId: 'flutter-firebase-auth-e2d0d',
    authDomain: 'flutter-firebase-auth-e2d0d.firebaseapp.com',
    storageBucket: 'flutter-firebase-auth-e2d0d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc1XeuEIOVwG3mb0KZdbwUd0GFx39kO5A',
    appId: '1:862048823819:android:a306905744670d3f17f50e',
    messagingSenderId: '862048823819',
    projectId: 'flutter-firebase-auth-e2d0d',
    storageBucket: 'flutter-firebase-auth-e2d0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2VXTId3qzcaob4BI-90j9b-NfrDZIuWQ',
    appId: '1:862048823819:ios:ad4f7ca2acf3fa2117f50e',
    messagingSenderId: '862048823819',
    projectId: 'flutter-firebase-auth-e2d0d',
    storageBucket: 'flutter-firebase-auth-e2d0d.firebasestorage.app',
    iosClientId: '862048823819-md84n2pg8cq520243o4ii8qmfkbhmk4e.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookAudio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2VXTId3qzcaob4BI-90j9b-NfrDZIuWQ',
    appId: '1:862048823819:ios:ad4f7ca2acf3fa2117f50e',
    messagingSenderId: '862048823819',
    projectId: 'flutter-firebase-auth-e2d0d',
    storageBucket: 'flutter-firebase-auth-e2d0d.firebasestorage.app',
    iosClientId: '862048823819-md84n2pg8cq520243o4ii8qmfkbhmk4e.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookAudio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD71HIt8GCjVA48kWlVI5OJ_MD_ampyrUE',
    appId: '1:862048823819:web:5477c99a5b35d58017f50e',
    messagingSenderId: '862048823819',
    projectId: 'flutter-firebase-auth-e2d0d',
    authDomain: 'flutter-firebase-auth-e2d0d.firebaseapp.com',
    storageBucket: 'flutter-firebase-auth-e2d0d.firebasestorage.app',
  );
}
